// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1g6jfOvqUijtcyEuKQlenaZ52EFqHOM',
    appId: '1:232463404838:web:b5780e4560d79e6bf0bbe7',
    messagingSenderId: '232463404838',
    projectId: 'nester-d3198',
    authDomain: 'nester-d3198.firebaseapp.com',
    storageBucket: 'nester-d3198.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEJleOdcb4i1nQbP9gh_OcS_bFeoS6d-I',
    appId: '1:232463404838:android:45e9699a7cd51298f0bbe7',
    messagingSenderId: '232463404838',
    projectId: 'nester-d3198',
    storageBucket: 'nester-d3198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7bR58EgdWUCTxWyEov-8UgPM3ndlz3TI',
    appId: '1:232463404838:ios:4a297893e53b5a50f0bbe7',
    messagingSenderId: '232463404838',
    projectId: 'nester-d3198',
    storageBucket: 'nester-d3198.appspot.com',
    iosBundleId: 'com.example.eventTicketingMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7bR58EgdWUCTxWyEov-8UgPM3ndlz3TI',
    appId: '1:232463404838:ios:a67c650f27d52b9ef0bbe7',
    messagingSenderId: '232463404838',
    projectId: 'nester-d3198',
    storageBucket: 'nester-d3198.appspot.com',
    iosBundleId: 'com.example.eventTicketingMobileApp.RunnerTests',
  );
}
